# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: exhibit
    main: ./cmd/exhibit/main.go
    ldflags: -s -w
    binary: exhibit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
  - id: keycap
    main: ./cmd/keycap/main.go
    ldflags: -s -w
    binary: keycap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
  - id: mdtoansi
    main: ./cmd/mdtoansi/main.go
    ldflags: -s -w
    binary: mdtoansi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
